[package]
name = "aerobox-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.6.0"
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
env_logger = "0.11.3"
dotenv = "0.15.0"
aws-config = "1.5.0"
aws-sdk-s3 = "1.32.0"
anyhow = "1.0.86"
